# Generated by Django 5.0.4 on 2024-04-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('person_name', models.CharField(max_length=20)),
                ('person_city', models.CharField(max_length=20)),
                ('storage_mode', models.CharField(choices=[('SIM', 'sim'), ('PHONE', 'phone')], max_length=10)),
            ],
        ),
    ]
